import { defaultTheme } from '@/themes/default';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        height: '100%',
        width: '100%',
        backgroundColor: '#a5d8ff',
        padding: 30,
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 10,
    },
    chartContainer: {
        width: '100%',
        height: '45%',
        padding: 10,
        borderColor: defaultTheme.colors.primary,
        borderWidth: 2,
        borderRadius: 28,
        backgroundColor: 'white',
        zIndex: 1,
    },
    audioProgress: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 10,
    },
    progressBar: {
        flex: 1,
        height: 4,
        backgroundColor: 'white',
        borderRadius: 2,
        marginLeft: 8,
    },
    graphHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        width: '100%',
        marginVertical: 10,
    },
    dropDownPicker: {
        borderColor: defaultTheme.colors.primary,
        borderWidth: 2,
    },
    tagButtonGroup: {
        flexDirection: 'row',
        borderColor: defaultTheme.colors.primary,
        borderWidth: 2,
        padding: 4,
        borderRadius: 30,
        gap: 8,
    },
    tagButton: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
    },
    observationHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginTop: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 10,
    },
    textArea: {
        backgroundColor: defaultTheme.colors.surface,
        borderColor: defaultTheme.colors.primary,
        borderWidth: 2,
        borderRadius: 10,
        padding: 10,
        minHeight: 80,
        maxHeight: '20%',
        height: 'auto',
        marginTop: 6,
    },
    disabledInput: {
        opacity: 0.6,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 20,
    },
    saveButton: {
        backgroundColor: defaultTheme.colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        width: '50%',
        alignItems: 'center',
    },
    deleteButton: {
        backgroundColor: '#ff3b30',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        width: '40%',
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
    },
});
